### ISSUE TITLE
[ Init ] Create Gamza bat

### ISSUE THREAD

**Issue by wuzoo** [GAMZA-BAT/algohub-client#1]
### 🔨 Issue

감자밭을 생성합니다.

### ✅ To-do

- [x] 감자밭 생성
- [x] 초기세팅
- [x] 폴더구조 잡기
- [x] theme 설정

**Comment by hwangjokim** [comment]
우리 파일중에 워크플로우나, 아니면 CSEY같은거 박혀있는것들 쳐내야하는데 제가 PR 올릴까요?

**Comment by j-nary** [comment]
> 우리 파일중에 워크플로우나, 아니면 CSEY같은거 박혀있는것들 쳐내야하는데 제가 PR 올릴까요?

그거 코리로 달아주랑 ! 초기세팅 한꺼번에 할겡
