### ISSUE TITLE
workflow pr labeler에 pnpm-lock.yml파일 exclude 하기

### ISSUE THREAD

**Issue by hwangjokim** [GAMZA-BAT/ALGOHUB-CLIENT#10]
### 🔨 Issue

pnpm은 킹받게 Lock을 yml으로 만드는 악취미가 있어서 xl pr로 만들어버리네요

### ✅ To-do

- [ ] 한줄 추가하기

**Comment by j-nary** [comment]
이거 제가 했습니당 제 biome 초기세팅 머지 되면 될 것 가탕용

**Comment by hwangjokim** [comment]
최고
