### ISSUE TITLE
UserDashboard 페이지 구현

### ISSUE THREAD

**Issue by j-nary** [GAMZA-BAT/algohub-client#45]
### 🔨 Issue

UserDashboard 페이지 구현

### ✅ To-do

- [ ] UserDashboard 페이지 구현
- [ ] UserCard 구현

### 📄 Reference

<img width="634" alt="image" src="https://github.com/user-attachments/assets/89c4ab57-38fc-4f8c-be5d-8a06eb359bdb">

**Comment by nourakhy** [comment]
install this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)
